name: LincolnBridgesNetwork
favicon: null
layout_spectrum: 0.05032765679061413
typography_spectrum: 0.5802689413540065
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1274885549210012
  lightness: 0.7350784800946712
  saturation: 0.09582358156330884
  rhythmicContrast: 0.9399302075617015
purpose: []
